[snowflake]
user = "joao"
password = "Oscarwilde2018"
account = "rlmmytx-pu52214"  # Exemplo: "abc12345.us-east-1"
warehouse = "compute_wh"
database = "TrabalhoSemestral2024"
schema = "ProjetoParte3"
